% Auto-generated by cameraCalibrator app on 15-Jun-2016
%-------------------------------------------------------

%% clear
%% Define images to process C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3
imageFileNames = { ...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage1.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage2.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage3.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage4.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage5.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage6.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage7.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage8.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage9.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage10.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage11.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage12.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage13.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage14.jpg',...
    'C:\Users\baymin\Documents\GitHub\matlab\StereoCalib\cali3\L\Limage15.jpg' ...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 3;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

%% Hgrid2cam
len = 15;
T = zeros(4,4,len);
for i = 1:len
    T(4,4,i) = 1;
    T(1:3,1:3,i) = stereoParams.CameraParameters1.RotationMatrices(:,:,i)';
    T(1:3,4,i) = stereoParams.CameraParameters1.TranslationVectors(i,:)';
end

Hgrid2cam = T;

%% Hmarker2world
PoseName = ["1", "10", "11", "12", "13", "14", "15", ...
             "2", "20", "3", "4", "5", "6", "7", "8", "9"];
nn = 15;
T = zeros(4,4,nn);
for ii = 1:nn
    % filename = "RobotPose" + PoseName(ii) + ".txt";
    filename = "Image" + num2str(ii) + ".txt";
    fid = fopen(filename);
    Data1 = textscan(fid, '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f');
    Mat1 = cell2mat(Data1);
    Mat1(1:3, 4) = Mat1(1:3, 4) * 1000;
    T(:,:,i) = Mat1;
end

Hmarker2world = T;

%% hand eye calibration
[Hcam2marker_, err] = TSAIleastSquareCalibration(Hmarker2world, Hgrid2cam);
